name: Manual testiny test run
on:
  workflow_dispatch:
    inputs:
      feature-flag:
        description: Enter Feature Flag -> Comma separated
        required: false
        default: ''
      revision-key:
        description: Enter Revision Key
        required: false
        default:  ''

env:
# General environmental variables
  MAILOSAURAPIKEY: ${{ secrets.MAILOSAURAPIKEY }}
  UK_STRIPE_KEY: ${{ secrets.UK_STRIPE_KEY }}
  IE_STRIPE_KEY: ${{ secrets.IE_STRIPE_KEY }}
  FEATURE_FLAG: ${{ github.event.inputs.feature-flag }}
  REVISION_KEY: ${{ github.event.inputs.revision-key }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
  SLACK_CHANNEL: C09QJ9XPJAX
  TESTINY_API_KEY: ${{secrets.TESTINY_API_KEY}}
# DEV environmental variables
  DEV_apiUsername: ${{ secrets.DEV_APIUSERNAME }}
  DEV_apiPassword: ${{ secrets.DEV_APIPASSWORD }}
  DEV_staffPassword: ${{ secrets.DEV_STAFFPASSWORD }}
# PROD environmental variables
  PROD_apiUsername: ${{ secrets.PROD_apiUsername }}
  PROD_apiPassword: ${{ secrets.PROD_APIPASSWORD }}
  PROD_staffPassword: ${{ secrets.PROD_STAFFPASSWORD }}
  
jobs:
  cleanup-appointments:
    name: 🧹 Cleanup Appointments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install dependencies
        run: npm i

      - name: Cleanup appointments
        run: node ./support/utils/cleanup_appointments.js dev_eu

  test:
    name: 🧪 E2E Tests
    timeout-minutes: 60
    needs: cleanup-appointments
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Add feature flags
      run: node ./support/utils/add_feature_flags.js ${{ env.FEATURE_FLAG }}
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Make notify-slack.sh executable
      run: chmod +x ./slack_results/notify-slack.sh
    - name: Notify Slack
      if: always() && !cancelled()
      run: ./slack_results/notify-slack.sh
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         CI_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - uses: actions/upload-artifact@v4
      if: always() && !cancelled()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
    - name: Upload results to Testiny
      if: success() || failure()
      run: |
        chmod +x ./testiny-importer-linux
        ./testiny-importer-linux testrun \
          --folder-separator "" \
          --enable-nested-folders \
          --apikey ${{ env.TESTINY_API_KEY }} \
          -y \
          -P GM \
          --junit playwright-results/results.xml \
          --name "Playwright_Testrun_$(date +'%Y-%m-%d_%H-%M-%S')"
